package: yakme
version: 0.0.1
author: Yakme - Yakamara CommonBundle for REDAXO
supportpage: www.redaxo.org/de/forum/

requires:
    redaxo: '>=5.3'
    packages:
        media_manager: '^2.0'
        mediapool: '^2.0'
    php:
        version: '>=7'

html_section_options:
    - Yakme\Html\SectionOption\AppendHtml
    - Yakme\Html\SectionOption\Attributes
    - Yakme\Html\SectionOption\Html
    - Yakme\Html\SectionOption\PrependHtml
